### ISSUE TITLE
DLAU Defect - Error during Deny Access Group Processing

### ISSUE THREAD

**Issue by mpradny** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#1]
Hi, 

 we are trying to run the DLAU in a pretty big environment - 15k+ users, 100+ servers and we got an error during Deny Access group processing.
![image](https://user-images.githubusercontent.com/12035342/225601894-827551fb-af27-4014-9f85-4daf3b44e5f8.png)

I tried to check the code, but the line number does not seem to match, so I'm not sure what exactly causes the problem. There are over 1000 Deny access groups. According to the log it crashed after getting to M* group, so it was roughly half-way through the list.

Any idea what to check?

Running DLAU 1.0.10 on Win 12.0.1FP1 Notes client.

Thanks,

Martin

**Comment by notesboy** [comment]
@mpradny are you available for me to review this error with you?

If you are, please reach out to me brian.arnold@hcl.com

**Comment by notesboy** [comment]
This error is caused when a large number of Deny Access Groups (25+) are listed on the Domino server document when there are also a large number of Domino servers documents (25+).

A better approach is to have a single Deny Access Group that lists all other Deny Access Groups that are currently on the Domino server documents. Then on the Domino server document, you only need to list the single Deny Access Group name.

The Domino License Analysis Utility will then scan for the additional Deny Access Groups recursively until all Members of those Groups are discovered.
