### ISSUE TITLE
Error with DA directories users

### ISSUE THREAD

**Issue by jdeniau35** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#10]
Hi

Still got an issue with DA, I needed to correct extra space in code: lscore.lss > GetDADirectories Line 19

adminServer=GetAdminValue("    AdminServer")(0) -> adminServer=GetAdminValue("AdminServer")(0)

In the dialog box for extrenal user I can't select any directory nor organisation, but got the users scan by checking both option in dialog box for external users

**Comment by notesboy** [comment]
This issue has been identified and will be available in the next release (V1.0.12)
