### ISSUE TITLE
DLAU Feature Request: "One click to complete"

### ISSUE THREAD

**Issue by KunioMatsuo** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#11]
"One click to complete" feature will be useful to skip clicking 4 steps.  Based on the condition most of organization does not have external users, 4 clicks are not required for those organization.  This feedback came from my customer.

**Comment by notesboy** [comment]
There is user interaction that is required at the end of the "Domino Environment Scan" that is very important for CCB/CCX calculations.

Allowing for the entire process to run without the opportunity to interact with the scan process would not allow the user to indicate how they indicate CCX licenses.
