### ISSUE TITLE
DenyAccessRead is not required but NetModfier is enough as Role in names.nsf to run the checker

### ISSUE THREAD

**Issue by KunioMatsuo** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#12]
Customer Feedback.  In the first run, proper setting of DenyAccessRead in ACL of names.nsf is required.

![image](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/124328865/1c6d6601-487c-4e2a-886c-8d93af32a4b5)

However, after testing many combination of ACL, it turned out to be ONLY NetModfier role is enough to run the tool.

**Comment by notesboy** [comment]
Either ACL role will provide the required access to the Domino Directories "Deny Access Groups" View.

We reference the ACL Role "DenyAccessRead" as it is used to secure the "Deny Access Groups" view.
