### ISSUE TITLE
Big Warning or Complete Explanation about "Not access server" in Secury tab in server document.

### ISSUE THREAD

**Issue by KunioMatsuo** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#13]
This feedback originally came from my customer.

This is not DLAU issue but product issue.  Most of admins do not know "what is requirement to disable users COMPLETELY", Their (mis)understanding is just add those users to deny group. No clear explanation is provided except small and short product documentation.

I propose big warning or complete explanation about "Not access server" in Secury tab in server document BEFORE starting tool in the Wizard.  Otherwise most customers will be in panic or puzzled why deny user is 0 while there are exactly some deny groups. Then they will find at last small explanation in the product documentation.  It gives them bad impression.

FYI: To avoid the issue I posted an enhancement request.

Add "Set also to "Not access server"" button next to Deny Access (groups/users) in Domino Server document. 
https://domino-ideas.hcltechsw.com/ideas/ADMIN-I-142

**Comment by thampel** [comment]
Closing this request for DLAU since the request is for the Domino Server or the Domino Directory template. It will be tracked as feature request for the product in the Domino ideas portal : reference [ADMIN-I-142](https://domino-ideas.hcltechsw.com/ideas/ADMIN-I-142)
