### ISSUE TITLE
DLAU V1.0.11 do not report Authorized users correctly

### ISSUE THREAD

**Issue by umeshm1979** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#15]
While auditing one of our customer's Domino environments.

So i used DLAU V 1.0.11 and something strange is reported.

The tool report about 6150 Authorized users but only about 400 exist in their NAB.

what it reports is that some Directory assistance is taken :

![image](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/133116658/a79a148d-184c-469a-bed6-daa0e02ca89c)

But both directories are not available for authentication and are not enabled at all :

![image](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/133116658/780d34e7-d4c5-411c-b06b-9346916b4839)

Can you tell us what is wrong here?

**Comment by notesboy** [comment]
Fixed in V1.0.12
