### ISSUE TITLE
Directories in Directory Assistance causing error despite being disabled

### ISSUE THREAD

**Issue by cbrandlehner** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#16]
I could reproduce an error with entries in a da.nsf.

Version 1.0.11 ignores the setting "Basic - Enabled" - "No".
![Bildschirmfoto 2023-05-23 um 15 08 35](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/10800971/9271ed56-9f99-47b2-ad5f-0038970bb719)

As a workaround you have to use "Domino - Replica1 - Enabled" - "No".
![Bildschirmfoto 2023-05-23 um 15 09 13](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/10800971/83498413-2982-48b2-8a1c-d45b8c5ed305)

**Comment by notesboy** [comment]
This has been resolved in DLAU V1.1.0
