### ISSUE TITLE
Deny Access Users not count from the group

### ISSUE THREAD

**Issue by kerozen54** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#17]
Hi, using the latest version 1.0.12, and now, this is the Deny Acces group that is not correctly count:

![image](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/25516195/1b9980dd-3f52-4f94-9db8-f58f825b52ab)
![image](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/25516195/6ad5da5b-a0fc-47b1-958a-179474bd9c85)

**Comment by notesboy** [comment]
Please verify that you have reviewed all Observations that were recorded (on the Navigator, click on "Observations" and then open the "Current Results" document.

If there are any "Security Observations", those will be affecting the "Deny Access Users" counts.

Make all suggested corrections for the Observations and then re-run the scans again to obtain cleaner results.

If you would like to discuss this during an online meeting, please reach out to me directly (brian.arnold@hcl.com).

**Comment by kerozen54** [comment]
Hi, you were right.
I Follow the security observations to enable internet and ldap port to enforce access and now the Deny access users is good.
Many thanks for your help.
