### ISSUE TITLE
Use of Directory Assistance (and secondary Domino Directory) not detected

### ISSUE THREAD

**Issue by slapraik-intec** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#18]
Hi.

Tried using the latest 1.0.12 version today.

DLAU did not detect that some servers in the environment are enabled to use Directory Assistance.  These servers are configured with a second Domino Directory for web user authentication.

**Comment by notesboy** [comment]
This is a Known Limitation and will be addressed in a future version of DLAU.

https://opensource.hcltechsw.com/domino-license-analysis-utility-DLAU/limitations/#directory-assistance-on-servers-other-than-administration-server
