### ISSUE TITLE
"GetListOfOrgs" onlly support two organizations

### ISSUE THREAD

**Issue by richardliuhq** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#22]
It seems the "GetListOfOrgs" function at the "slCore" library only support two organizations and previous organization will be overwritten if there are two or more organizations at the Domino directory DB.
Please check enclosed lines of code and suggested codes below. Thanks

					'//Following two lines overwrite organizations if there are multiple organizations  
					'''''''''ReDim Preserve orgArray(x)   
					'''''''''orgArray(x)=colVar(y)
					
					ReDim Preserve orgArray(UBound(orgArray)+1)  
					orgArray(UBound(orgArray))=colVar(y)

**Comment by notesboy** [comment]
Thank you @richardliuhq for uncovering this code defect.

We are testing the code adjustment now and will be soon releasing a new version of the DLAU (V1.1.1) with this correction.
