### ISSUE TITLE
What causes the Environment Scan process not to complete?

### ISSUE THREAD

**Issue by RikakoKitajima** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#23]
We used V1.1.0. 
Since the following log message, the process has not completed overnight and there are no error messages. 
　　　In "CheckServerSettings" - checking for Entitlement Tracking apps
Please advise what the possible causes are and what to investigate.

**Comment by notesboy** [comment]
The Domino Environment Scan for 40 Domino servers should not take more than 30 minutes to complete, so it is my opinion that it has failed for some reason.

You will need to take a look at the Scan Log to determine why the scan did not complete. I can assist with this investigation once you send me the content of the Scan Log.


To access the Scan Log, the client must follow these steps:

1. Locate and select the DLAU Notes application on the Notes Workspace (do not open)
2. From the Notes Menu, select "View -> Go To ..." and then select the View "All Documents"
3. In the "All Documents" View, open the document under the Category "1. Scan Log"
4. Once the Scan Log is opened, select all contents of the Scan Log and send to HCL (me)
