### ISSUE TITLE
FIELD VALIDUSERCOUNT ERROR

### ISSUE THREAD

**Issue by supportMas** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#24]
Hi support ,

we run Domino License Analysis Utility

after click on view report , when fill "your information" field we have an error

in attach details 

![error licensing](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/140529122/bd15ff7b-10e3-4fcd-b5e8-58facaa7e889)
![yourinformation tab](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/140529122/e6eb0b1f-c3fb-4c83-989e-390804907f17)

**Comment by notesboy** [comment]
This issue has been resolved in V1.1.2 (new version as of 12PM ET on July 25, 2023)

**Comment by supportMas** [comment]
Same error with new version
![FIELDerrorV1 12](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/140529122/0567b6ab-5e0b-4b12-8c30-7d8242bd2fce)
