### ISSUE TITLE
change domino server for check

### ISSUE THREAD

**Issue by supportMas** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#25]
Hi Support

primary domino server is down and HCL Domino License Analysis Utility try to connect that server
is it possible use another domino server ? is there a procedure ? thanks
 in attach the error
![primaryfailed](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/140529122/1ba1133d-5524-4f16-a33b-e8a4927d31f7)

**Comment by notesboy** [comment]
the Administration Domino Server must be running in order for DLAU to operate correctly.

If it is not running and/or has been decommissioned, you must select a different Domino Administration server for your environment.

Selecting the Domino Administration server is performed in the Access Control List Settings for the Domino Directory ("Advanced" tab of ACL dialog)
