### ISSUE TITLE
FIELD VALIDUSERCOUNT ERROR again

### ISSUE THREAD

**Issue by supportMas** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#26]
Hi support ,

we run Domino License Analysis Utility last version

after click on view report , when fill "your information" field we have same error

in attach details
![FIELDerrorV1 12](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/140529122/5babf0fb-a7b4-40a5-b8bb-7f08b94cd302)

**Comment by notesboy** [comment]
Please contact me directly so that I can setup a web meeting for us to review this error in more detail.

brian.arnold@hcl.com
