### ISSUE TITLE
DLAU Defect: When clicking "Start Environment Scan Now" nothing happens (V1.1.3)

### ISSUE THREAD

**Issue by uwebrahm** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#27]
When clicking "Start Environment Scan Now" nothing happens (V1.1.3)
After signing I've tried to click the "Start Environment Scan Now" - nothing happens.
Running from a local Notes client 12.0.2 FP1

**Comment by uwebrahm** [comment]
After signing I've tried to click the "Start Environment Scan Now" - nothing happens.
Running from a local Notes client 12.0.2 FP1

**Comment by notesboy** [comment]
The DLAU requires the Notes Client to have the JavaScript Options in the Notes Preferences enabled. If those are not enabled, the button click events in the DLAU will not function.

To enable JavaScript in your Notes Client, click on "File -> Preferences", switch to the "Basic" settings, then make sure "Enable JavaScript" and "Enable JavaScript error dialogs" are both enabled

![image](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/67094/f556686f-ff12-4479-9203-9933ab2c667d)
