### ISSUE TITLE
External Users box is missing a yes/no option

### ISSUE THREAD

**Issue by bels-ap** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#28]
Besides the typo in the last sentence (Usrrs) there should be a "yes/no" option to answer the question correctly, if there are external users or known guests in the environment.

<img width="394" alt="image" src="https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/56879557/65640856-1f49-435c-b9ff-624a41eb9946">

this is related to HCL Domino License Analysis Utility (V1.1.3)

**Comment by notesboy** [comment]
This has been changed to display "yes" and "No" buttons in V1.1.4
