### ISSUE TITLE
Observations with wrong content

### ISSUE THREAD

**Issue by bels-ap** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#29]
Some observations have a wrong content. In the attached image, the last three entries mention "License Tracking not running" but the Details describe the DA configuration for LDAP. The first three entries about License Tracking are correct though.

![image](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/56879557/8c115717-70cd-4934-a573-256e12980277)

DLAU V1.1.3

**Comment by bels-ap** [comment]
Could it be that DLAU is not honoring group names in the configuration document and therefore reports that a server is not using licensing tracking? 
![image](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/56879557/06f306b9-e46b-440f-b8b7-c42c6171ef0b)

**Comment by notesboy** [comment]
If there are any Security Observations, it is those that will cause DLAU to ignore most of the users in any Deny Access Groups that are listed on your Domino Server documents.

More specifically, if you are seeing either the "HTTP" or "LDAP" Security Observations, those are what can cause DLAU to ignore Deny Access Groups. If the HTTP and LDAP ports are not enforcing the use of Server Access Settings, all settings on the Security tab of the Server document will be ignored.

https://opensource.hcltechsw.com/domino-license-analysis-utility-DLAU/observations/

**Comment by OpenSourceTemplateDominoDev** [comment]
> Some observations have a wrong content. In the attached image, the last three entries mention "License Tracking not running" but the Details describe the DA configuration for LDAP. The first three entries about License Tracking are correct though.
> 
> ![image](https://user-images.githubusercontent.com/56879557/256861208-8c115717-70cd-4934-a573-256e12980277.png)
> 
> DLAU V1.1.3

@bels-ap Can you please confirm if the server name shown in the UI is duplicated with a `|` character in it?

**Comment by bels-ap** [comment]
in the Observation Details on the right, yes, I confirm

**Comment by OpenSourceTemplateDominoDev** [comment]
Thanks, this will be fixed in 1.2.1

**Comment by OpenSourceTemplateDominoDev** [comment]
This was fixed in DLAU 1.2.1
