### ISSUE TITLE
ERROR: Object variable not set [#: 91, line: 3)

### ISSUE THREAD

**Issue by slapraik-intec** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#3]
Hi.

Trying to run the analysis tool on a Domino 12.0.2 server.  The initial Domino Environment Scan appears to complete and presents info about Admin server, other Domino servers, etc. But when I click on [Next] I get the above error reported.

Thanks.
Simon

**Comment by slapraik-intec** [comment]
Closing the application and starting again seems to have got passed the issue.

**Comment by notesboy** [comment]
This has now been resolved in the upcoming release V1.0.11
