### ISSUE TITLE
Store Customer Name, HCL Customer, etc. in a configuration document

### ISSUE THREAD

**Issue by thampel** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#31]
When performing DLAU Scans on a regular base, at the end for each report you have to enter Customer Name, HCL Customer Number and so on manually.
Wouldn't it make sense to store these informationen in a "configuration document" to be reused at each scan?

Source: https://domino-ideas.hcltechsw.com/ideas/DOMINO-I-2499

**Comment by thampel** [comment]
This is tracked as DNEXT-23784 and will be addressed in the next version 1.2.1

**Comment by OpenSourceTemplateDominoDev** [comment]
This was fixed in DLAU 1.2.1
