### ISSUE TITLE
Support running the User Report Tool on a Domino server

### ISSUE THREAD

**Issue by slapraik-intec** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#33]
Hi.

We have tried and it seems that the User Report Tool (64bit) runs just as well (if not better) on a Domino server than it does on a Notes client.

Please can this be added as a supported option and the documentation updated.
Thanks.

**Comment by thampel** [comment]
Intentionally we designed the standalone User Report Tool to run from a workstation because often customers do not accept making changes to the server or installing extra tools on the server.
