### ISSUE TITLE
Wrong user information logged

### ISSUE THREAD

**Issue by hallieym** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#35]
![WrongUserInfo](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/23041473/3d6d3305-8f02-4e5e-b709-792eff52eadb)

In this example there are two errors.

- The user does not have a Manager access to that database (CertReq.nsf)
- The database is not on that Server.

**Comment by notesboy** [comment]
This information is being pulled from another system in the Domino environment (if you are running V12 it obtains the information from the Entitlement Tracking System, if pre-V12 it obtains the information from the User Report Tool).

If the file CertReq.nsf is not showing up in the "File -> Application -> Open" dialog in your Notes Client, launch your Domino Administrator client, access the Domino server listed on the document, switch to the "Files" tab and search for the CertReq.nsf from there.

**Comment by hallieym** [comment]
Domino is V12. Do you know how to correct the Information?

I did search from the "Files" tab. This database is on another Domino server, with the same name but not a "2" in the end of it.

**Comment by regelmol** [comment]
Same problem here. DLAU reports databases that don't even exist (on that server, but another one) or have been deletet or the ACL has been corrected. How can I update this information after the correction of ACL issues?

**Comment by bels-ap** [comment]
HCL doesn't know.. I have a support ticket open and need to try a few things, like deleting the entitlements database, let it recreate over night (which the server in my case didn't do) and then run another report to see if it has been fixed

**Comment by regelmol** [comment]
Now I wonder why this issue has been closed by @notesboy . DLAU is completely unreliable and thus unusable with such issues.

**Comment by bels-ap** [comment]
Short update from my case, there is an issue with the entitlement tracking as it's not being updated anymore after the first run. Of course the DLAU report will always be wrong, if the entitlement is providing wrong/outdated content.

**Comment by thampel** [comment]
Can you please work with our [support team](https://support.hcltechsw.com/csm) to analyze this issue? Entitlement tracking is supposed to update information daily and keep this information for some time.

**Comment by bels-ap** [comment]
already doing so Thomas, the case I'm referring to is with HCL Support

**Comment by hallieym** [comment]
> Short update from my case, there is an issue with the entitlement tracking as it's not being updated anymore after the first run. Of course the DLAU report will always be wrong, if the entitlement is providing wrong/outdated content.

Thanks for the update @bels-ap. I also made a case I'm waiting on.

**Comment by regelmol** [comment]
I've got an open case as well and the same problem in two other environments.

**Comment by bels-ap** [comment]
btw, we received a Domino HF which fixed the problem, it only needs to be installed on the admin server of the infrastructure

**Comment by regelmol** [comment]
Great. But I wonder how a HF on the admin server fixes wrong information in the ncf files on the spokes...

**Comment by hallieym** [comment]
There is now a defect article about this bug.
https://support.hcltechsw.com/csm?id=kb_article&sysparm_article=KB0111129

**Comment by hallieym** [comment]
> Great. But I wonder how a HF on the admin server fixes wrong information in the ncf files on the spokes...

You need to delete the ncf file and the nsf file and wait for them to be recreated.

**Comment by regelmol** [comment]
> There is now a defect article about this bug. https://support.hcltechsw.com/csm?id=kb_article&sysparm_article=KB0111129

Thanks
