### ISSUE TITLE
Links in result form open wrong view

### ISSUE THREAD

**Issue by eknori** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#37]
The link for Mail Users and Deny Access Users open the Deny Access Group view instead of UserInfo

![image](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/3882620/d3347337-7e56-4f75-affb-e076953987ae)

**Comment by notesboy** [comment]
this has been corrected in V1.1.6 (released Sept. 14 @ 8:30AM ET)
