### ISSUE TITLE
Hotspot still points to the wrong view

### ISSUE THREAD

**Issue by eknori** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#39]
The hotspots in V1.1.6 for "Deny Access Users" still open the "dagroups" view instead of "UserInfo"

![image](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/3882620/ad144a9f-9989-4099-9958-dfa6e43806d4)

**Comment by thampel** [comment]
Tracked as DNEXT-23780 and will be fixed in the next release 1.2.1

**Comment by OpenSourceTemplateDominoDev** [comment]
This is fixed in [V1.2.1](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/releases)
