### ISSUE TITLE
DLAU Feature Request

### ISSUE THREAD

**Issue by Megabusa** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#4]
Hi,

It has long been good practice within Notes/Domino to have an Application signer ID. Specifically for signing production databases
Its my understanding that in the past such a ID would have fallen outside of user license count as it's being used solely for the purpose of administering a Domino environment. e.g. Stopping dev apps from running in the wild on a production server.
Could there be a new feature in order to specify a signer ID during the wizard so that although it's still detected It doesn't count towards a CCB or CCX license.
You could allow a NAB lookup to select user/s and then perhaps validate these against the Domino server programmability restrictions in the server document. 

Maybe

**Comment by thampel** [comment]
Hi
it is a best practice to have application signer ID's, especially for fine tuning client side permissions (ECL).
However, according to the [Domino License Terms](https://www.hcltechsw.com/resources/license-agreements) any ID with access to the server is to be counted.
An ID that is only used for signing the application does not need to have access to the server - so only if the user ID is not allowed to access the server, it will not be counted.
