### ISSUE TITLE
DLAU will NOT detect CCX in EDC not saved in root directory

### ISSUE THREAD

**Issue by KarlHartmann** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#41]
CCX not detected from EDC

you canrt compare a dtabase FILENAME against something that my contain folder parts

	' if an external directory was chosen to identify CCX users, check to see if the current directory is the one that was chosen
	If GetAdminValue("DAListExternal")(0)<>"" Then 
		tmpVal=GetAdminValue("DAListExternal")
		tmpVal=Split(tmpVal(0),"!!")
		externalNABName=Left(tmpVal(1),Len(tmpVal(1))-1)
		If LCase(processNAB.Filename)=externalNABName Then externalNAB=t
	End If

BAD LS programming

**Comment by thampel** [comment]
This bug is tracked as DNEXT-23856 and will be fixed in the next version 1.2.1

**Comment by OpenSourceTemplateDominoDev** [comment]
This is fixed in [V1.2.1](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/releases)
