### ISSUE TITLE
CCX not properly detected by OU/Org

### ISSUE THREAD

**Issue by KarlHartmann** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#42]
CCX not properly detected by  OU/Org
since you check for some string   (Orgs only)
in user name - you may hit  CommonName parts too

BAD programming

					If externalNAB Then userNote.ExternalNAB="true"
				If externalORGs(0)<>"" Then 
					For x=0 To UBound(externalORGs)
						If InStr(1,userNote.FullName(0),externalORGs(x),5)<>0 Then userNote.ExternalORG="true":Exit For
					Next
				End If

**Comment by notesboy** [comment]
In order for DLAU to detect potential external users, at this time they must be identified either by an Org/OrgUnit that is selected from a list or by the Person documents being located in a secondary Domino Directory.

Users with only a Common Name cannot be used for identification as an External user at this time.

**Comment by KarlHartmann** [comment]
IF you want to idetify a perosn by it's OU/Org ONLY
THEN 
you should check the code
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
this code, as taken from DLAU 1.1.5   checks for   OU ond or ORG within the FULLNAME
as a RESULT   if  Org  ist just part of the  Common Name  you'll get a positiv  (CCX) match

if InStr(1,userNote.FullName(0),externalORGs(x),5)<>0 Then us

Please FIX DLAU at this point 

happy programming 
CHarly
