### ISSUE TITLE
The DLAU shows an ex employee as active with internet password set

### ISSUE THREAD

**Issue by NabilHocine** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#43]

**Comment by thampel** [comment]
The tool just reports the current access settings in your environment. Please make sure the server access settings are configured correctly for all protocols. See [this reference](https://opensource.hcltechsw.com/domino-license-analysis-utility-DLAU/observations/#security-observations)

**Comment by NabilHocine** [comment]
It shows some users "ex employee " as active user.
our configuration are correct and you may connect and check by your self.

Kindly advise
