### ISSUE TITLE
The DLAU shows an ex employee as active with internet password set / issue number 2

### ISSUE THREAD

**Issue by NabilHocine** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#44]
The DLAU shows an ex employee as active with internet password set

It shows some users "ex employee " as active user.
our configuration are correct and you may connect and check by your self.

Kindly advise

**Comment by NabilHocine** [comment]
Dears,
appreciate your support, our configurations are correct, but many inactive users are listed on active users list.

Best regards,

**Comment by thampel** [comment]
In order to toubleshoot your problem we need log files to be uploaded. Since they contain sensitive data, we'd like you to open a support ticket rather than posting them here in a public forum
