### ISSUE TITLE
CCX not properly detected by OU/Org   - it's a BUG in the code 

### ISSUE THREAD

**Issue by KarlHartmann** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#53]
reporting again, since my first one was just closed
https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/issues/42

CCX not properly detected by OU/Org
since you check for some string (Orgs only)
in user name - you may hit CommonName parts too

Dear developer, please read and understand your code - and our error about NotesNames

You MUST not search by  INSTR  for an OU or ORG sting in a Notes Fullname
you might get a result by hitting part  of the common name

BAD programming

				If externalNAB Then userNote.ExternalNAB="true"
			If externalORGs(0)<>"" Then 
				For x=0 To UBound(externalORGs)
					If InStr(1,userNote.FullName(0),externalORGs(x),5)<>0 Then userNote.ExternalORG="true":Exit For
				Next
			End If

**Comment by notesboy** [comment]
Fixed for DLAU V1.2.5
