### ISSUE TITLE
Exceed 64k bytes.

### ISSUE THREAD

**Issue by jongminkimkr** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#56]
When run domino license analysis utility, "There was an Error in the (CheckLicenseTrackingSettings) function. The details of the Error are below: Error: Notes error: adding entry will cause text list to exceed 64K Entry not added. #: 4000  line #: 109" error occur.

**Comment by notesboy** [comment]
This is a duplicate of https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/issues/32
