### ISSUE TITLE
Error: To open database on remote machines

### ISSUE THREAD

**Issue by dpastov** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#57]
Error: To open database (CN=myserver.com/O=Org!!names.nsf) on remote machines the server where the agent is running has to be listed by remote machine as trusted server (#: 4164 , line #: 74)

**Comment by notesboy** [comment]
More information about your specific usage is required.
- Are you attempting to run the DLAU Scans as a Scheduled Agent?
- Are you, as the person running DLAU, able to access the Domino Directory on the server listed in the error message?

**Comment by dpastov** [comment]
> Are you attempting to run the DLAU Scans as a Scheduled Agent?

No, I run it manually (on Local PC). 

> Are you, as the person running DLAU, able to access the Domino Directory on the server listed in the error message?

No, I'm not.

**Comment by thampel** [comment]
Ok, this works as designed. DLAU can of course not access servers that dont exist anymore or that the user you are running with is not cross certified/not allowed to access. Please grant admin access to that server.
