### ISSUE TITLE
Directory Assistance db with a space in filename is no longer recognized by DLAU V1.2.1

### ISSUE THREAD

**Issue by notesboy** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#61]
If the Directory Assistance Catalog db filename contains a space (e.g. "Directory Assist.nsf"), DLAU V1.2.1 no longer recognizes the Directory Assistance and states that "Directory Assistance is not configured".

This is not an issue with the same Domino environment using DLAU V1.2.0

**Comment by OpenSourceTemplateDominoDev** [comment]
This cannot be reproduced so closing
