### ISSUE TITLE
Selected Org/OrgUnit in the Known Guest Identification dialog are not marked as Known Guests.

### ISSUE THREAD

**Issue by Sjaksan** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#64]
We have multiple addressbooks in de da.nsf.  In the Known Guest Identification dialog its only possible to select one addressbook for the Known Guests, so i want to use the Org/OrgUnit selector. 
When I use the Org/OrgUnit for the selection, the users are not marked as Known Guest, while they are in a external NAB and have maximum read access. 
I'm using DLAU V.1.2.2.

**Comment by OpenSourceTemplateDominoDev** [comment]
Does the address book entries in the da.nsf contain the term "external"? If not, please add that and try again. I thought that was a requirement. CC @thampel for thoughts.

**Comment by dougprominic** [comment]
I've added an additional issue with what I believe is a workable fix at https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/issues/66

**Comment by notesboy** [comment]
Fixed for DLAU V1.2.5

Associated GitHub bug https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/issues/71
