### ISSUE TITLE
Known guests specified by org calculating as CCB due to missing logic + one fix

### ISSUE THREAD

**Issue by dougprominic** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#66]
The issue is where the logic should be setting the user to known guest as long as it does not have any > reader access (since it's trying to disqualify IsReader based on matching any higher level) at 229 of ProcessEntitlements in the slCore:
```
            If isReader And externalNAB Then 
                userNote.KnownGuest = "true" 'DNEXT-23857
            End If    
```
 
However back at 264 of GetPersonDocuments userNote.ExternalNAB = "true" gets set for users in external NABs (logically) but not for external orgs:
```
                If externalNAB Then
                    userNote.ExternalNAB = "true"
                End If
                
                If externalORGs(0) <> "" Then 
                    For x = 0 To Ubound(externalORGs)
                        If Instr(1, userNote.FullName(0), externalORGs(x), 5) <> 0 Then 
                            userNote.ExternalORG = "true"
                            Exit For
                        End If
                    Next
                End If
```
 
Starting at line 155 of ProcessEntitlements the ONLY way that externalNAB is set is based on filepath:
```
        externalNAB = False
        ' if an external directory was chosen to identify CCX users, check to see if the current directory is the one that was chosen
        If GetAdminValue("DAListExternal")(0) <> "" Then 
            tmpVal = GetAdminValue("DAListExternal")
            tmpVal = Split(tmpVal(0), "!!")
            
            ' START - DNEXT-23856
            currentFilePath = Lcase(userNote.NABPath(0))
            externalFilePath = Lcase(Replace(tmpVal(1), ")", ""))
            
            If currentFilePath = externalFilePath Then 
                externalNAB = True
```
 
Nowhere in the entitlement script does it check for ExternalOrg, so the agent never updates these users to qualify as known guests as it would if they were in DA directories instead of identified by an external org.  So the doc is never set to Known Guest.  Then checking the user information view the licenseType gets set to CCB by default and then without the known guest flag on the user doc it can't categorize them out.

I fixed this in my local install by adding to the slCore library -> Process Entitlements at line 172 (just after the DA List External check):
 ```
        If userNote.externalOrg(0) = "true" Then
	         externalNAB = True
	    End If	
```
	    
This ended with known guest/CCX orgs properly calculating by their ACL access.

**Comment by notesboy** [comment]
Fixed for DLAU V1.2.5

Associated GitHub bug https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/issues/71
