### ISSUE TITLE
DLAU Defect: "Calculating" remains in Deny Access Groups in Summary Page.

### ISSUE THREAD

**Issue by KunioMatsuo** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#7]
**Reproducing Procedure**

1. Install and Setup new Notes and Domino environment.
2. Create a user and a Deny Access Group, and add the user to the group.
3. Run DLAU.
4. See screenshot and log below.  No error observed in the log.  I recognize "The HCL Domino server "domino/HCL" is not using any Deny Access Groups to secure server access"  in the log.  As no explanation is provided about this message, I can not recognize this is problem or not.
5. "Calculating" remains desplayed even after 12 hours.

**Screenshots**
![image](https://user-images.githubusercontent.com/124328865/231923619-08b1bb08-6389-4406-862f-78c4755dc3d6.png)
![image](https://user-images.githubusercontent.com/124328865/231923690-3717ea7e-e5c6-4c10-b88f-00df6b5b7b6e.png)

**Log**
4/14/2023 11:05:52 AM	In "(PullInfoConfig)" agent
4/14/2023 11:05:52 AM	Starting "GetAdminServerInfo" function"
4/14/2023 11:05:52 AM	"GetAdminServerInfo" - begin
4/14/2023 11:05:52 AM	In "GetAdminServerInfo" - svrName = CN=domino/O=HCL
4/14/2023 11:05:52 AM	"GetAdminServerInfo" - GetServerList - begin
4/14/2023 11:05:52 AM	The HCL Domino Server "domino/HCL" is not properly secured for HTTP traffic
4/14/2023 11:05:52 AM	The HCL Domino Server "domino/HCL" is not properly secured for LDAP traffic
4/14/2023 11:05:52 AM	"GetAdminServerInfo" - GetServerList - finished
4/14/2023 11:05:52 AM	"GetAdminServerInfo" - CheckUserAccess - begin
4/14/2023 11:05:52 AM	"CheckUserAccess" - begin
4/14/2023 11:05:52 AM	"CheckUserAccess" - finished
4/14/2023 11:05:52 AM	"GetAdminServerInfo" - CheckUserAccess - finished
4/14/2023 11:05:52 AM	"GetAdminServerInfo" - finished
4/14/2023 11:05:52 AM	Finished "GetAdminServerInfo" function"
4/14/2023 11:05:52 AM	Starting "CheckServerSettings" function"
4/14/2023 11:05:52 AM	"CheckServerSettings" - begin
4/14/2023 11:05:52 AM	In "CheckServerSettings" - locating Admin server doc
4/14/2023 11:05:52 AM	In "CheckServerSettings" - Admin server doc located
4/14/2023 11:05:52 AM	In "CheckServerSettings" - checking for Directory Assistance info
4/14/2023 11:05:52 AM	In "CheckServerSettings" - checking for Entitlement Tracking apps
4/14/2023 11:05:52 AM	In "CheckServerSettings" - checking for License Tracking apps
4/14/2023 11:05:52 AM	The License Tracking task is not running on the HCL Domino server: "domino/HCL|domino/HCL"
4/14/2023 11:05:52 AM	"CheckServerSettings" - finished
4/14/2023 11:05:52 AM	Finished "CheckServerSettings" function"
4/14/2023 11:05:52 AM	"(PullInfoConfig)" agent finished
4/14/2023 11:06:00 AM	In "(PullInfoUser)" agent
4/14/2023 11:06:00 AM	Obtaining Domino Directory
4/14/2023 11:06:00 AM	Obtaining Person document information
4/14/2023 11:06:00 AM	"GetPersonDocuments" - begin
4/14/2023 11:06:00 AM	Scanning Person documents in the Domino directory -"HCLMail's Directory" (domino/HCL!!names.nsf)
4/14/2023 11:06:00 AM	# of Person documents in Domino Directory = 2
4/14/2023 11:06:00 AM	"GetPersonDocuments" - finished
4/14/2023 11:06:00 AM	"(PullInfoUser)" agent finished
4/14/2023 11:06:09 AM	In "(PullInfoDAGroups)" agent
4/14/2023 11:06:09 AM	Obtaining Domino Directory
4/14/2023 11:06:09 AM	Obtaining Deny Access Groups"
4/14/2023 11:06:09 AM	"GetDenyAccessGroups" - begin
4/14/2023 11:06:09 AM	**The HCL Domino server "domino/HCL" is not using any Deny Access Groups to secure server access**
4/14/2023 11:06:09 AM	"ProcessDenyAccessNames" - begin
4/14/2023 11:06:09 AM	"ProcessDenyAccessNames" - finished
4/14/2023 11:06:09 AM	"GetDenyAccessGroups" - finished
4/14/2023 11:06:09 AM	"(PullInfoDAGroups)" agent finished
4/14/2023 11:06:24 AM	In "(PullInfoEntitlement)" agent
4/14/2023 11:06:24 AM	Retrieving Entitlement Information
4/14/2023 11:06:24 AM	Scanning Entitlement system
4/14/2023 11:06:24 AM	"(PullInfoEntitlement)" agent finished

**Comment by notesboy** [comment]
This has been corrected for the next release of the DLAU (V1.0.11)
