### ISSUE TITLE
Wrong categorization in "User Information" view due to spelling mistake

### ISSUE THREAD

**Issue by perlausten** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#70]
There's a spelling error in the categorized column in the "User Information" view:

```
licenseType := @If(@IsError(aclLevel); "< Unknown >";
	(aclLevel = "Author" | aclLevel = "Depositor" | aclevel = "Reader" | aclLevel = "No Access"  | aclLevel = "") & (extNAB + extORG != "") ; "CCX"
	; "CCB Users");
```

The `aclevel = "Reader"` check should be `aclLevel = "Reader"`.

This leads to CCX users with reader access being categorized as CBB users.

**Comment by notesboy** [comment]
Fixed for DLAU V1.2.5
