### ISSUE TITLE
External (CCX) Users Who Are Not Listed in Entitlement Tracking Are Being Recognized as CCB Users when selecting External Organization

### ISSUE THREAD

**Issue by stevepridemore** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#71]
[External (CCX) Users Who Are Not Listed in Entitlement Tracking Are Being Recognized as CCB Users](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/issues/47) is still a problem.  If you select your external users based on Organization instead of directory they are still being flagged as CCB instead of CCX if they are not listed or haven't been calculated in the entitlements database.  

In the  ProcessEntitlements function of the slCore script library.  
The If statement starting on line 229
```
If isReader And externalNAB Then 
      userNote.KnownGuest = "true" 'DNEXT-23857
End If
```
Should be changed to 
```
If isReader And (externalNAB Or userNote.externalOrg(0) = "true") Then 
      userNote.KnownGuest = "true" 'DNEXT-23857
 End If
``` 

and the If statement starting on line 233 
```
If externalNAB Then 
     userNote.KnownGuest = "true"    'DNEXT-23857
End If
``` 
should be changed to  
```
If externalNAB Or userNote.externalOrg(0) = "true" Then 
     userNote.KnownGuest = "true"    'DNEXT-23857
End If
```

**Comment by notesboy** [comment]
Fixed for DLAU V1.2.5
