### ISSUE TITLE
Add an option to edit the choice for External User Directory

### ISSUE THREAD

**Issue by dcisigner** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#73]
DLAU does not work in our environment. We use Directory Assistance to include a custom database containing our contractors and other containing our clients with access to our systems. These databases do not include the expected forms (i.e. Person, Group), subforms or views, so DLAU can only report CCB users in our address book.  When it asks for an directory containing external org known guests, if it could provide a way to specify the server and location of a directory containing those, then it would work for us.

**Comment by notesboy** [comment]
We have adjusted the design of DLAU to check for every Design Element that is used during the Domino Directory Design Check.

this does not mean that we can support custom Domino Applications that are configured to be used as a possible Domino Directory. Throughout DLAU, we access Fields that must be on the discovered Person documents. If the Fields do not exist (which would be the case for many custom Domino applications mimicking a Domino Directory) the scans will fail.

It would be near to impossible to include a Field Mapping function to allow users to indicate which Fields in their custom Domino application to use in relation to the Fields that already exist in a Domino Directory that is using the Domino directory template design.

**Comment by dcisigner** [comment]
Can you not just look for a specific view to be populated in custom 
applications that are included in Directory Assistance?

Don Deal
IT Manager
Direct Contact, Inc.
www.directcontact.com
630-485-5700 Ext 110



From:   "Brian Arnold" ***@***.***>
To:     "HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU" 
***@***.***>
Cc:     "dcisigner" ***@***.***>, "Author" 
***@***.***>
Date:   09/30/2024 04:48 PM
Subject:        Re: 
[HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU] Add an option to 
edit the choice for External User Directory (Issue #73)



We have adjusted the design of DLAU to check for every Design Element that 
is used during the Domino Directory Design Check.
this does not mean that we can support custom Domino Applications that are 
configured to be used as a possible Domino Directory. Throughout DLAU, we 
access Fields that must be on the discovered Person documents. If the 
Fields do not exist (which would be the case for many custom Domino 
applications mimicking a Domino Directory) the scans will fail.
It would be near to impossible to include a Field Mapping function to 
allow users to indicate which Fields in their custom Domino application to 
use in relation to the Fields that already exist in a Domino Directory 
that is using the Domino directory template design.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by dcisigner** [comment]
Brian,

I should have mentioned, we have a database using the Domino Directory 
design that has an agent running every hour that syncs Person documents 
with documents in our Contractors and Clients databases.  I don't know the 
history of who created this or why, but if the DLAU process would allow 
the user to select a database for external/known users instead of only 
providing a list of databases included in Directory Assistance that have 
the required design elements (forms, subforms, views, etc), then DLAU 
would probably work for us.

Don Deal
IT Manager
Direct Contact, Inc.
www.directcontact.com
630-485-5700 Ext 110



From:   "Brian Arnold" ***@***.***>
To:     "HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU" 
***@***.***>
Cc:     "dcisigner" ***@***.***>, "Author" 
***@***.***>
Date:   09/30/2024 04:48 PM
Subject:        Re: 
[HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU] Add an option to 
edit the choice for External User Directory (Issue #73)



We have adjusted the design of DLAU to check for every Design Element that 
is used during the Domino Directory Design Check.
this does not mean that we can support custom Domino Applications that are 
configured to be used as a possible Domino Directory. Throughout DLAU, we 
access Fields that must be on the discovered Person documents. If the 
Fields do not exist (which would be the case for many custom Domino 
applications mimicking a Domino Directory) the scans will fail.
It would be near to impossible to include a Field Mapping function to 
allow users to indicate which Fields in their custom Domino application to 
use in relation to the Fields that already exist in a Domino Directory 
that is using the Domino directory template design.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by notesboy** [comment]
DLAU looks at much more than just the information that is provided by the View Columns.

It performs a deeper analysis of the data that is stored in the individual Fields on the Person, Server, and Group documents. These values are not available in the Views themselves, so DLAU looks at the various Field values.

this is where it becomes near to impossible to analyze a custom Domino application that is being used as a potential Domino Directory. If the Fields that DLAU analyzes do not exist in the custom Domino application (which would be most likely), the various DLAU Scans will fail.
