### ISSUE TITLE
Allow DLAU to run without all those Buttons and questions

### ISSUE THREAD

**Issue by KarlHartmann** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#76]
at least for subsequent runs - it would be great to have all questions and selections saved withon DLAU
so that it can be run again after responding to ONE question (run with latest settings)

**Comment by thampel** [comment]
We are working on an integrated License dashboard where admins will be able to see the figures in an always-current dashboard, without having to click buttons and without having to answer questions every time.

**Comment by notesboy** [comment]
This is a duplicate of https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/issues/52
