### ISSUE TITLE
DLAU Defect: "Calculating" remains in Deny Access Groups in Summary Page.

### ISSUE THREAD

**Issue by KunioMatsuo** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#8]
**Reproducing Procedure**
If Deny Access Group name is not listed in "Not Server Access" in "Security" tab in Server document, this happens.  This message remains appeared.

**Issue**
Users will be puzzled.
"Calculating" is misleading.  "Unable to Calculate.  Check Observatin page" will be batter for users, otherwise users will wait for long long time as instruction says it takes several hours.

This should be fixed or add FAQ and/or documentation, or replace the message other than "Calculating".

**Screenshots**
![image](https://user-images.githubusercontent.com/124328865/231929701-fae64692-3dae-4cf5-ada0-73be18ff47c0.png)

**Log**
4/14/2023 11:05:52 AM	In "(PullInfoConfig)" agent
4/14/2023 11:05:52 AM	Starting "GetAdminServerInfo" function"
4/14/2023 11:05:52 AM	"GetAdminServerInfo" - begin
4/14/2023 11:05:52 AM	In "GetAdminServerInfo" - svrName = CN=domino/O=HCL
4/14/2023 11:05:52 AM	"GetAdminServerInfo" - GetServerList - begin
4/14/2023 11:05:52 AM	The HCL Domino Server "domino/HCL" is not properly secured for HTTP traffic
4/14/2023 11:05:52 AM	The HCL Domino Server "domino/HCL" is not properly secured for LDAP traffic
4/14/2023 11:05:52 AM	"GetAdminServerInfo" - GetServerList - finished
4/14/2023 11:05:52 AM	"GetAdminServerInfo" - CheckUserAccess - begin
4/14/2023 11:05:52 AM	"CheckUserAccess" - begin
4/14/2023 11:05:52 AM	"CheckUserAccess" - finished
4/14/2023 11:05:52 AM	"GetAdminServerInfo" - CheckUserAccess - finished
4/14/2023 11:05:52 AM	"GetAdminServerInfo" - finished
4/14/2023 11:05:52 AM	Finished "GetAdminServerInfo" function"
4/14/2023 11:05:52 AM	Starting "CheckServerSettings" function"
4/14/2023 11:05:52 AM	"CheckServerSettings" - begin
4/14/2023 11:05:52 AM	In "CheckServerSettings" - locating Admin server doc
4/14/2023 11:05:52 AM	In "CheckServerSettings" - Admin server doc located
4/14/2023 11:05:52 AM	In "CheckServerSettings" - checking for Directory Assistance info
4/14/2023 11:05:52 AM	In "CheckServerSettings" - checking for Entitlement Tracking apps
4/14/2023 11:05:52 AM	In "CheckServerSettings" - checking for License Tracking apps
4/14/2023 11:05:52 AM	The License Tracking task is not running on the HCL Domino server: "domino/HCL|domino/HCL"
4/14/2023 11:05:52 AM	"CheckServerSettings" - finished
4/14/2023 11:05:52 AM	Finished "CheckServerSettings" function"
4/14/2023 11:05:52 AM	"(PullInfoConfig)" agent finished
4/14/2023 11:06:00 AM	In "(PullInfoUser)" agent
4/14/2023 11:06:00 AM	Obtaining Domino Directory
4/14/2023 11:06:00 AM	Obtaining Person document information
4/14/2023 11:06:00 AM	"GetPersonDocuments" - begin
4/14/2023 11:06:00 AM	Scanning Person documents in the Domino directory -"HCLMail's Directory" (domino/HCL!!names.nsf)
4/14/2023 11:06:00 AM	# of Person documents in Domino Directory = 2
4/14/2023 11:06:00 AM	"GetPersonDocuments" - finished
4/14/2023 11:06:00 AM	"(PullInfoUser)" agent finished
4/14/2023 11:06:09 AM	In "(PullInfoDAGroups)" agent
4/14/2023 11:06:09 AM	Obtaining Domino Directory
4/14/2023 11:06:09 AM	Obtaining Deny Access Groups"
4/14/2023 11:06:09 AM	"GetDenyAccessGroups" - begin
4/14/2023 11:06:09 AM	**The HCL Domino server "domino/HCL" is not using any Deny Access Groups to secure server access**
4/14/2023 11:06:09 AM	"ProcessDenyAccessNames" - begin
4/14/2023 11:06:09 AM	"ProcessDenyAccessNames" - finished
4/14/2023 11:06:09 AM	"GetDenyAccessGroups" - finished
4/14/2023 11:06:09 AM	"(PullInfoDAGroups)" agent finished
4/14/2023 11:06:24 AM	In "(PullInfoEntitlement)" agent
4/14/2023 11:06:24 AM	Retrieving Entitlement Information
4/14/2023 11:06:24 AM	Scanning Entitlement system
4/14/2023 11:06:24 AM	"(PullInfoEntitlement)" agent finished

**Comment by notesboy** [comment]
This has been corrected for the next release of the DLAU (V1.0.11)
