### ISSUE TITLE
DLAU Defect: When "Enforce server access settings" in "Internet Ports" -> "Directory" in server document to "Yes", "Calculating" remains as "Authorized Users".

### ISSUE THREAD

**Issue by KunioMatsuo** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#9]
When "Enforce server access settings" in "Internet Ports" -> "Directory" in server document to "No", "Authorized Users" shows numbers.

Log shows nothing special.

2023/04/25 11:15:58	In "(PullInfoConfig)" agent
2023/04/25 11:15:58	Starting "GetAdminServerInfo" function"
2023/04/25 11:15:58	"GetAdminServerInfo" - begin
2023/04/25 11:16:05	In "GetAdminServerInfo" - svrName = CN=domino/O=HCL
2023/04/25 11:16:05	"GetAdminServerInfo" - GetServerList - begin
2023/04/25 11:16:05	"GetAdminServerInfo" - GetServerList - finished
2023/04/25 11:16:05	"GetAdminServerInfo" - CheckUserAccess - begin
2023/04/25 11:16:05	"CheckUserAccess" - begin
2023/04/25 11:16:05	"CheckUserAccess" - finished
2023/04/25 11:16:05	"GetAdminServerInfo" - CheckUserAccess - finished
2023/04/25 11:16:05	"GetAdminServerInfo" - finished
2023/04/25 11:16:05	Finished "GetAdminServerInfo" function"
2023/04/25 11:16:05	Starting "CheckServerSettings" function"
2023/04/25 11:16:05	"CheckServerSettings" - begin
2023/04/25 11:16:05	In "CheckServerSettings" - locating Admin server doc
2023/04/25 11:16:05	In "CheckServerSettings" - Admin server doc located
2023/04/25 11:16:05	In "CheckServerSettings" - checking for Directory Assistance info
2023/04/25 11:16:05	"GetDADirectories" - begin
2023/04/25 11:16:05	"GetDADirectories" - finished
2023/04/25 11:16:05	In "CheckServerSettings" - checking for Entitlement Tracking apps
2023/04/25 11:16:05	In "CheckServerSettings" - checking for License Tracking apps
2023/04/25 11:16:05	The License Tracking task is not running on the HCL Domino server: "domino/HCL|domino/HCL"
2023/04/25 11:16:05	"CheckServerSettings" - finished
2023/04/25 11:16:05	Finished "CheckServerSettings" function"
2023/04/25 11:16:05	"(PullInfoConfig)" agent finished
2023/04/25 11:16:11	In "(PullInfoUser)" agent
2023/04/25 11:16:11	Obtaining Domino Directory
2023/04/25 11:16:11	Obtaining Person document information
2023/04/25 11:16:11	"GetPersonDocuments" - begin
2023/04/25 11:16:11	Scanning Person documents in the Domino directory -"HCL Mail's Directory" (domino/HCL!!names.nsf)
2023/04/25 11:16:11	# of Person documents in Domino Directory = 5
2023/04/25 11:16:11	"GetPersonDocuments" - finished
2023/04/25 11:16:11	"(PullInfoUser)" agent finished
2023/04/25 11:16:19	In "(PullInfoDAGroups)" agent
2023/04/25 11:16:19	Obtaining Domino Directory
2023/04/25 11:16:19	Obtaining Deny Access Groups"
2023/04/25 11:16:19	"GetDenyAccessGroups" - begin
2023/04/25 11:16:19	"ProcessDenyAccessNames" - begin
2023/04/25 11:16:19	"ProcessDenyAccessNames" - finished
2023/04/25 11:16:19	"GetDenyAccessGroups" - finished
2023/04/25 11:16:19	"(PullInfoDAGroups)" agent finished
2023/04/25 11:16:28	In "(PullInfoEntitlement)" agent
2023/04/25 11:16:29	Retrieving Entitlement Information
2023/04/25 11:16:29	Scanning Entitlement system
2023/04/25 11:16:29	"(PullInfoEntitlement)" agent finished

![image](https://user-images.githubusercontent.com/124328865/234158279-857edd57-f3c0-4695-b774-66a7e35f5c2e.png)

**Comment by notesboy** [comment]
This has been corrected for the next release of the DLAU (V1.0.11)
